// Generated-header sniff — ARCHITECTURE.md §6, `generated` detector's second
// confidence source ("path + header sniff").
//
// This runs during measure/, reusing the head sample already read for
// tokenization (tokens.ts) — no extra I/O, and it's why detect/generated.ts
// itself never touches file content: the result is precomputed onto
// FileRecord.generatedHeader before any detector runs.

const MARKERS = [
  /@generated\b/,
  /\bDO NOT EDIT\b/i,
  /\bcode generated\b.*\bdo not edit\b/i,
  /\bthis file is automatically generated\b/i,
  /\bauto-generated\b/i,
];

export function looksGenerated(headSample: string): boolean {
  if (headSample === "") return false;
  return MARKERS.some((re) => re.test(headSample));
}
