import { test } from "node:test";
import assert from "node:assert/strict";
import { looksGenerated } from "./header.js";

test("looksGenerated: recognizes common generated-file banners", () => {
  assert.equal(looksGenerated("// @generated by protoc-gen-go\n"), true);
  assert.equal(looksGenerated("/* Code generated by mockgen. DO NOT EDIT. */"), true);
  assert.equal(looksGenerated("// This file is automatically generated, do not edit.\n"), true);
});

test("looksGenerated: ordinary source content is not flagged", () => {
  assert.equal(looksGenerated("export function hello() { return 1; }\n"), false);
});

test("looksGenerated: empty sample is not flagged", () => {
  assert.equal(looksGenerated(""), false);
});
